spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://voyagerss.com:3306/fn_statistic?characterEncoding=utf8&serverTimezone=UTC&useUnicode=true&createDatabaseIfNotExist=true
    username: fn
    password: dugodwk1
#  data:
#    mongodb:
#      host: mongodb://fn:dugodwk1@voyagerss.com/fn?serverSelectionTimeoutMS=5000&connectTimeoutMS=10000
#      database: fn

db-mysql:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://voyagerss.com:3306/fn_statistic?characterEncoding=utf8&serverTimezone=UTC&useUnicode=true&createDatabaseIfNotExist=true
  username: fn
  password: dugodwk1



#error / warn / debug / info / trace
logging:
  level:
    sql: error
    p6psy.p6spy: info
    root: warn
  file:
    path: /var/log/${spring.application.name}-release
    name: ${logging.file.path}/${spring.application.name}.log

