server:
  port: 34000
spring:
  decorator:
    datasource:
      p6spy:
        logging: slf4j
        enable-logging: on
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://voyagerss.com:3306/fn_statistic?characterEncoding=utf8&serverTimezone=UTC&useUnicode=true&createDatabaseIfNotExist=true
    username: fn
    password: dugodwk1
  jpa: #JPA 설정
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MariaDBDialect  #방언 설정 https://dololak.tistory.com/465, https://gigas-blog.tistory.com/119
        show_sql: true #하이버네이트가 실행하는 모든 SQL문을 콘솔로 출력해 준다.
        format_sql: true        #콘솔에 출력되는 JPA 실행 쿼리를 가독성있게 표현한다.
        use_sql_comments: true        #디버깅이 용이하도록 SQL문 이외에 추가적인 정보를 출력해 준다.
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#  data:
#    mongodb:
#      host: mongodb://fn:dugodwk1@voyagerss.com/fn?serverSelectionTimeoutMS=5000&connectTimeoutMS=10000
#      database: fn

db-mysql:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://voyagerss.com:3306/fn_statistic?characterEncoding=utf8&serverTimezone=UTC&useUnicode=true&createDatabaseIfNotExist=true
  username: fn
  password: dugodwk1
  
file:
  upload-dir: /ftp
#OAuth2
encodeKey: secret
#REST API
kakao.client.id: e32a4d819f76b2ca4e652a2477ecf982
#kakao pay
kakao.admin.key: 9182554bcd6244da75828cfed4e62a65
#app:
ecos-api-key: A3KS6JOGXDYWDBC2XQ3Y
ecos-api-url: http://ecos.bok.or.kr
fred-api-key: 458b9943916b312467be56c964760715


devtools: #jsp파일 서버 재시작 없이 바로 적용하기  spring-boot-devtools
  livereload:
    enabled: true
    
    
--- #batch 환경
spring:
  config:
    activate:
      on-profile: batch
  batch:
    job:
      enabled: true
      names: ${job.name:NONE}
    initialize-schema: never
logging: # ROOT레벨 전체 로깅 레벨 결정
  level:
    root: info
    com.god.bo.test: info #com.god.bo.test 패키지 logging Level > info
    com.god.bo.test.controller: debug #com.god.bo.test.controller 패키지 logging Level > debug
--- #dev 환경
spring:
  config:
    activate:
      on-profile: dev
#  datasource: #TODO : dev용으로 변경 필요
#    url: jdbc:log4jdbc:mariadb://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=UTC
#    hikari:
#      username: root
#      password: qlalfqjsgh

--- #api 환경
spring:
  config:
    activate:
      on-profile: api
#  datasource: #TODO : prod용으로 변경 필요
#    hikari:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: fn
#      password: dugodwk1
#      jdbc-url: jdbc:mysql://voyagerss.com:3306/fn_statistic?characterEncoding=utf8&serverTimezone=UTC&useUnicode=true&createDatabaseIfNotExist=true

logging: # ROOT레벨 전체 로깅 레벨 결정
  level:
    root: info

springdoc:
  version: '1.0.0'
  api-docs:
    groups:
      enabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match: /**

